### ISSUE TITLE
Question: Why need the EqualityComparer for SourceCache.EditDiff()

### ISSUE THREAD

**Issue by shtse8** [RolandPheasant/DynamicData#110]
First of all, thanks to your rich library and it helps my a lots for managing collections.

After studying the documentation and some tries, I would like to sync two list (including updates, adds and removes). I have implemented my own extension like this:
```C#
        public static void EditSync<TItem, TKey>(this SourceCache<TItem, TKey> oldItems, IEnumerable<TItem> newItems)
        {
            oldItems.Edit(innerList =>
            {
                newItems = newItems.AsArray();
                var removeItems = innerList.Items.Except(newItems);
                innerList.Remove(removeItems);
                innerList.AddOrUpdate(newItems);
            });
        }
```

After that, I have found there is a `EditDiff` method for doing the same thing. But the only difference is it needs a EqualityComparer, I don't know what some I put it there because I have already given the key to the `SourceCache` constructor.

So I decided reading the source code to figure out the reason.
https://github.com/RolandPheasant/DynamicData/blob/ec88df33d5a062296015ed5b3bd82ac70db24e91/DynamicData/Cache/Internal/EditDiff.cs#L21-L41

Still, I don't understand what is the reason behind. Could someone can give me a kindly explanation why we need to calculate the intersect and using the EqualityComparer to compare the values? And what I should pass it there if I just want to compare the key? Thanks.

**Comment by RolandPheasant** [comment]
The answer is very simple: The equality comparer ensures an item with exactly the same value does not get transmitted again.

To explain further:

Suppose you load all your data and 10,000 items items are returned. For the initial load, this will transmit a change set with 10,000 adds.  Later you reload all data which returns 10,000 items but only one row has been modified. Clearly it is more efficient for Dynamic Data if ```EditDiff``` returns a change set of 1 change rather than a change set of 10,000 changes. This ensures down stream operators have less work to do thus leading to a huge performance improvement.

Typically the equality comparer would compare a modified time stamp.

**Comment by RolandPheasant** [comment]
Just read your post again and realised I missed an import bit of your example:

Without the specific equality comparer the comparison would rely on the default equality (or custom equality) of the items in the cache.   For example, for fast equality comparison it is good practice to create equality based on a key. I do this as standard practise. When I need to determine whether an object is equal by value, I generate an equality comparer which compares all values on the object (using Resharper of course).   It may also be that that no equality is implemented on the object which means default equality is used.

Each of these 3 scenarios yields different results. Hence the enforcement of the comparer.

Years ago I wasted so much time diagnosing problems due to equality that I am always on guard against issue caused by it.

A great insight into equality and hash code calculation is here: https://blogs.msdn.microsoft.com/ericlippert/2011/02/28/guidelines-and-rules-for-gethashcode/

**Comment by shtse8** [comment]
Thanks for your detailed explanation.
I have one more question, for primitive types, I can easily understand what is equal. But for object instance, I don't fully understand what is equal and that's why I always not to implement the equality comparison.

For example, for two instances:
```C#
class Person
{
  int id;  
  string name;
  
  public Person(int id, string name) {
    this.id = id;
    this.name = name;
  }
}

Person oldA = new Person(1, "Kyle");
Person newA = new Person(1, "Anson");

if (oldA.Equals(newA)) oldA.Name = newA.Name;
```
I don't know they are equal or not. It always happens when I am updating the list, as there is a change in the list but I want to compare two object is the same for updating it. So everytime I implement the equality comparer, I only compare the `id`, once the `id` is the same, the equality comparer will always return true.

This is my standard implementation of `IEquatable<Person>`
```C#
class Person : IEquatable<Person> {

  int id;  
  string name;
  
  public Person(int id, string name) {
    this.id = id;
    this.name = name;
  }

  public bool Equals(Person other)
  {
      if (other is null) return false;
      if (ReferenceEquals(this, other)) return true;
      return Id.Equals(other.Id;
  }
}
```

Am I doing right for the Equals? Or it should depends on different case? If it's latter, how can the end user know what my Equals is comparing?

**Comment by RolandPheasant** [comment]
Equality is a huge topic and so much depends on what you want. Referring to the article which I linked, one of the guidelines states that if an item is ever added to a collection container the hash code should never change. The hash code is directly linked to equality so the hash and default equals should be calculated on the id field as it uniquely identifies the entity regardless of whether any values have changed.

Coming back to your example, I would ensure the default equality is based on the id. This enforces the guideline of the hash code never changing. For most cases in any system this is desireable and performs well.

The second use case is when editing an item or reloading an item from a repository we need to determine whether any of the values have changed. In this case I always introduce an secondary equality comparer.

Here is an example: 
https://github.com/RolandPheasant/DynamicData/blob/master/DynamicData.Tests/Domain/Person.cs which is a test object for dd.

You will see that default equality is based on a value which is immutable and never changes.  For comparing the mutable values I use the secondary “AgeComparer” which can be used and specified explicitly to see whether the entity is different to an entity with the same name. This is a simple test object so only compares age for testing. In practice I would compare all mutable values.


I hope this helps to clarify the question.

**Comment by RolandPheasant** [comment]
There is an active dad community on Slack.

If you want to join send me you email address to mailto:roland@dynamic-data.org and I will send an invite.

**Comment by shtse8** [comment]
I got it now. For my best understanding, `ChangeReason.Update` doesn't respect the inner item property changed event, it just mean the SourceList/SourceCache have updated it. As all my items inside the list have implemented `NotifyPropertyChanged` using `ReactUI.RaiseAndSetIfChanged()`. I thought the update event is according to the items event, even I call `AddOrUpdate()` with the same data many times. there shouldn't have any performance issue because the items will not raise any event.

**Comment by shtse8** [comment]
Oh, I am wrong. I should use `MergeMany` instead if I want to watch the items.
