### ISSUE TITLE
OnItemAdded and OnItemRemoved for SourceCache

### ISSUE THREAD

**Issue by shtse8** [RolandPheasant/DynamicData#111]
The apis for sourcelist and sourcecache are different. and there are some good apis of source list cannot be used in source cache. there are missing OnItemAdded and OnItemRemoved in source cache. At the moment, I still can use `.WhereReasonsAre(ChangeReason.Add)` to achieve the same goal. so this is not an issue.  just a suggest to make two apis better the same. for my understanding, source cache is dictionary (naming dictionary is better then cache?), while source list is collection. I hope I am correct and my suggestion is good for further development. this project is far amazing than any other reactive list. keep going!

**Comment by robsonj** [comment]
Would it make more sense to remove the OnItemXXX() methods from ISourceList? The WhereReasonsAre() seems like its more in the spirit or DD IMHO. Which both already have as you mention.

Removal is of course a breaking API change for people that may already be using the OnXXX() style methods.

**Comment by RolandPheasant** [comment]
@robsonj I agree wherereasonsare in more in the spirit on rx. However I know for sure that people are using the api I it is better not to break people.

The list api is smaller than the cache api. This is purely because of performance. When creating operators in general it is easier to achieve good performance with the cache as items can be looked up by key whereas with the list there are many operators which mandate looking up items using indexof as the index is not always known to the operator. For large change sets this can be very expensive. However I am willing to look at enriching the list, one operator at the time so long as performance can be achieved.

I also agree about the semantics of cache rather than dictionary. If I could go back in time I would have dispensed with list and cache and instead use ObservableDataSource<T> and ObservableDataSource<TObject, TKey>. Alas there are far too many consumers of dd to make such a wholesale change.

**Comment by robsonj** [comment]
I'm wondering if we could go in the opposite direction then and add a couple of extension methods to the SourceCache API which would give it parity with the SourceList API?
