### ISSUE TITLE
Can't combine SourceLists logically because of clear()

### ISSUE THREAD

**Issue by JKronberger** [RolandPheasant/DynamicData#16]
The below test fails

        [Fact]
        public void MergeManyShouldWork()
        {
            var a = new SourceList<int>();
            var b = new SourceList<int>();
            var c = new SourceList<int>();

            var parent = new SourceList<SourceList<int>>();
            parent.Add(a);
            parent.Add(b);
            parent.Add(c);

            var d = parent.Connect().MergeMany(e => e.Connect()).AsObservableList();

            d.Count.Should().Be(0);

            a.Add(1);

            d.Count.Should().Be(1);
            a.Add(2);
            d.Count.Should().Be(2);

            b.Add(3);
            d.Count.Should().Be(3);
            b.Add(5);
            d.Count.Should().Be(4);
            d.Items.Should().BeEquivalentTo(new[] {1, 2, 3, 5});

            b.Clear();

            // Fails below
            d.Count.Should().Be(2);
            d.Items.Should().BeEquivalentTo(new[] {1, 2});
        }

The __Clear()__ methods breaks the changeset because it cannot be combined with other change sets and totally blows away result.

**Comment by RolandPheasant** [comment]
I can confirm that the above fails!  It is due to an optimisation in several places within the list infrastructure.  I should be able to apply a fix within the next few days.  

Out of interest, are you trying to create a logical Or operator i.e. a.Or(b).Or(c) using MergeMany?

**Comment by bradphelan** [comment]
Trying to create a logical OR between two input lists.

A + B -> C

A.Clear() should only clear the elements of A from C

**Comment by RolandPheasant** [comment]
I have a local fix but have not pushed it to the build yet. I will try and get it in a beta build next weekend.

Also I have meaning for a while to create or, and, except and xor logic between 2 or more list. I will start the work very soon. 

These logical operators already exist for cache operators so if your objects have a unique key you can call .AddKey(...) and use the existing cache operators.

**Comment by RolandPheasant** [comment]
Just spied a problem with AddKey() and List combination. I will push to fix to both this week

**Comment by RolandPheasant** [comment]
@bradphelan @JKronberger 

I have applied a fix for the  problem and published a beta release for you to try.   So please update to the latest pre-release [Dynamic Data 4.2.2.1081-Beta](https://www.nuget.org/packages/DynamicData/4.2.2.1081-Beta) and let me know whether it works.  However I have some reservations about trying to create an ```Or``` operator from the ```MergeMany``` operator.

If you want a quick response or have any questions, feel free to contact me on the [Dynamic Data chat room](https://gitter.im/RolandPheasant/DynamicData)

**Consideration 1**

The first problem is that subsequent operators including ```AsObservableList``` utlisie the index of each change in order to prevent the expensive ```IndexOf``` list operator when reforming a target list.   This could lead to incorrect insertions and removes.  The solution in this case is to use the ```RemoveIndex``` as follows

```
 var d = parent.Connect()
		     .MergeMany(e => e.Connect().RemoveIndex())
		     .AsObservableList();
```

This forces adding new items to the end of a resultant list and using indexof when removing items.

**Consideration 2**

If the solution removes one or more child lists the consumer would have to clear the list first otherwise the ```MergeMany ``` operator would not receive a notification for the removal of the individual items 

**Consideration 3**

If an item exists in list a and in list b it appears in the result list. If the item is removed from either of these lists, a remove notification will be received and the item will subsequently be removed from the result list - this is  clearly incorrect as the item should remain in the result list

**Consideration 4 - Perhaps a solution for now**

if the items have a unique value they can be converted into cache items which already has a fully tried and tested Or operator.  This can be achieved as follows:

 1. Convert each list into a cache stream by calling the AddKey operator
 2. Use the cache's Or operator
 3. Remove the key so the stream becomes a list again

```
var a = new SourceList<int>();
var b = new SourceList<int>();
var c = new SourceList<int>();

var d = a.Connect().AddKey(t=>..\\return key)
		.Or(b.Connect().AddKey(t=>..\\return key))
		.Or(c.Connect().AddKey(t=>..\\return key))
		.RemoveKey()
		.AsObservableList();
```
I have never tried this so please let me know how you get on.  The limitation with this solution is the operator only works for a fixed number of lists

**Finally**

I will soon create dedicated Or operator for the source list.

**Comment by RolandPheasant** [comment]
I have coded the fist cut of logical collection operators.

See https://github.com/RolandPheasant/DynamicData/blob/master/DynamicData/List/Internal/Combiner.cs for a preview of the logic.

Should be able to write some unit tests and publish a beta version over the weekend

**Comment by RolandPheasant** [comment]
I have implement And, Or, Xor and Except operators for the observable list

You need to install this version [DynamicData 4.3.0.1086-Beta](https://www.nuget.org/packages/DynamicData/4.3.0.1086-Beta)

Now you can do this:
```
var a = new SourceList<int>();
var b = new SourceList<int>();
var c = new SourceList<int>();
var d = a.Connect().Or(b.Connect()).Or(c.Connect()).AsObservableList();
```
What you cannot do is dynamically add and remove lists from these collection operators. I will implement that in version 4.4

**Comment by bradphelan** [comment]
Looks great. I'll try to get around to looking at it but I'm sidetracked at
the moment. Thanks for updating the features. I'm sure they will be useful
:)
