### ISSUE TITLE
UWP and DynamicData question

### ISSUE THREAD

**Issue by byrialsen** [RolandPheasant/DynamicData#161]
Hi. 

I am a UWP developer and just discovered DynamicData when looking into frameworks as Reative Extensions/ReactivateUI. DynamicData looks very promising, but my problem is that I target Windows 10 LTSB 2016. Even though LTSB 2016 is the newest LTSB version it is build on a rather old version of Windows 10 (Anniversary Update = 14393). 

Anniversary Update only supports .Net Standard 1.4, thus I can't use DynamicData latest version as you upgraded to .Net Standard 2.0. You have made a comment that this is done as Reactive Rx only supports .Net Standard 2.0+, but actually Rx 4.1 seems to target UWP directly, so I can actually use RX 4.1 in my UWP apps targeting Anniversary Update.

Do you see any way for me at this point to be able to use DynamicData in an UWP with targets Anniversary Update? Could it be an idea in the future to be able to let DynamicData target UWP the same way as Rx does?

I know I can wait until Windows 10 LTSB 2019 is released as this version might support .Net Standard 2.0, but the problem could be the same over and over again as LTSB versions of Windows 10 are realeased with 2-3 years in between.

**Comment by glennawatson** [comment]
System.Reactive/ReactiveUI uses a package called MsBuild.Sdk.Extras to allow for UWP support. https://github.com/onovotny/MSBuildSdkExtras

https://github.com/dotnet/reactive/blob/master/Rx.NET/Source/src/System.Reactive/System.Reactive.csproj

As you can see in the TargetFrameworks it lists the UWP targets there which allows it to be crossed compiled.

It targets .net standard 2.0 as well instead of .net standard 1.4

**Comment by RolandPheasant** [comment]
I'll follow suit and hopefully can solve this one quickly

**Comment by RolandPheasant** [comment]
@byrialsen as per the advice of @glennawatson I have updated Dynamic Data to use MSBuildSdkExtras in order to support UWP.

I have built and published a branch would like you to test the generated packages [appveyor build](https://ci.appveyor.com/project/RolandPheasant/dynamicdata-dpbpa/build/artifacts). Please try the DynamicData package only as the ReactiveUI package will soon be removed from the solution. If this fixes the issue for you I will merge the changes into the main branch and publish a new version to Nuget.

Please ignore the build failure which is due to issues finding the test assemblies. I will fix this soon.

**Comment by byrialsen** [comment]
Hi @RolandPheasant 

I have installed the Nuget package with success into a blank UWP project targeting only Anniversary Update (14393). As I don't know much about how reactive programming works yet, I have copied some example from one of your snippets and it works, so I guess this is proof enough. 

Let me know if you want to check further before merging the changes.

**Comment by RolandPheasant** [comment]
That's enough for me thanks. I'll merge it tomorrow

**Comment by byrialsen** [comment]
I am the one saying thanks. Really nice/quick work. Thanks a lot.

**Comment by RolandPheasant** [comment]
I meant to do it last night but had a late work night. I should be able to publish it by Monday evening

**Comment by RolandPheasant** [comment]
Btw feel free to join the slack forum. Link is on dynamic data GitHub readme

**Comment by RolandPheasant** [comment]
v6.6.0 has been deployed to Nuget. Any issues, please let me know

**Comment by Feroks** [comment]
I started to have following error in Runtime, when i provide `ParallelisationOptions` to `Transform` method.
`Could not load type 'DynamicData.PLinq.ParallelisationOptions' from assembly 'DynamicData, Version=6.6.0.2492, Culture=neutral, PublicKeyToken=null'.`

I am building UWP application with Xmaarin.Forms. 
UWP version: 10.0.16299.0
XF version: 3.2.0.871581

**Comment by RolandPheasant** [comment]
I think I know what the issue is. I will take a look

**Comment by RolandPheasant** [comment]
@Feroks  would you mind grabbing the artefacts from here [Appveyor build](https://ci.appveyor.com/project/RolandPheasant/dynamicdata-dpbpa/builds/19814243)

It looks like it works for me, but I would like you to test it before I publish

**Comment by Feroks** [comment]
@RolandPheasant tried it. Works for me as well.
