### ISSUE TITLE
Thread safety issue with simple AddOrUpdate

### ISSUE THREAD

**Issue by yexcoffier** [RolandPheasant/DynamicData#197]
Hi,
this unit test fail :
```C#
[Test]
public async Task SourceCacheTest()
{
	for (int i = 0; i < 10000; i++)
	{
		var cache = new SourceCache<int, int>(x => x);
				
		Task.Run(() => cache.AddOrUpdate(1));

		await cache
			.Connect()
			.Timeout(TimeSpan.FromSeconds(5))
			.Catch<IChangeSet<int, int>, TimeoutException>(e => { Assert.Fail($"i = {i} | cache.Items.Count : {cache.Items.Count()}"); return Observable.Start(() => default(IChangeSet<int, int>)); })
			.FirstAsync();
	}
}
```

The loop number can vary, but I'm checking the number of items on failure and it's always 1 : 
Message: i = 185 | cache.Items.Count : 1
Message: i = 3 | cache.Items.Count : 1
Message: i = 134 | cache.Items.Count : 1

Any idea why ? It looks like a thread safety issue with AddOrUpdate (I tried the same thing with a SourceList, no problem).

I'm using DynamicData 6.7.1.2534 with .Net 4.7.

**Comment by RolandPheasant** [comment]
Interesting a similar test was carried out a long time ago to fix some threading issues. Since then there have been changes to the source cache (on the face of it minor). However I suspect that was when the issue was introduced.

**Comment by softlion** [comment]
I found you are using "lock" to synchronize operations. 

lock won't work correctly when used with Tasks. This is because the Task library use a thread pool and schedules part of methods (before and after the await keyword) on one or any thread pool thread (depending if ConfigureAwait(false) is used). This mean 2 async operations can execute on the same thread at the "same" time, preventing lock from working as expected, as lock only makes sure that 2 different threads can not access the code inside the lock. lock does not prevent the same thread from executing the locked code at the same time, which happens commoly when using Tasks.

You should use SemaphoreSlim instead.

I have a unit test demonstrating that lock does not work as expected with Tasks, so trust me.

**Comment by RolandPheasant** [comment]
There is a simple explanation for the issue which you are encountering. It's thread starvation. The clue is that the exception which you are trapping in a timeout exception. 

```Task.Run``` starts a task on the thread pool and in this case the thread pools quickly hits it's upper limit at which point a throttle kicks in. This is exasperated by awaiting ```FirstAsync``` which has it's own execution context which cannot be continued on until the thread pool has completed processing. Hence the timeouts.

**Comment by yexcoffier** [comment]
Interesting, I would have never thought about something like that, I did some other tests and you're right. I'll change my way of doing tests to avoid this problem.
Thank you for your time !
